baseURL = 'https://wwww.kylerassweiler.ca'
languageCode = 'en-us'
title = 'Kyle Rassweiler'
theme = 'ananke'
#RelativeURLs = true
#CanonifyURLs = true
DefaultContentLanguage = "en"
paginate = 10
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Kyle Rassweiler"
  favicon = "/images/favicon.ico"
  site_logo = "/images/LogoXSmall.png"
  youtube = "https://www.youtube.com/user/Krassweiler"
  odysee = "https://odysee.com/@kylerassweiler"
  github = "https://github.com/rassweiler"
  gitlab = ""
  twitter = ""
  linkedin = "https://www.linkedin.com/in/kylerassweiler/"
  featured_image = "/images/cover.png"
  description = "A sleek software portfolio"
  facebook = ""
  instagram = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3
  skillSection = "Skills"
  mainSections = ["Software"]

[languages]
  [languages.en]
    languageName = "English"
    title = "Kyle Rassweiler"
    subtitle = "A sleek software portfolio"
    owner = "Kyle Rassweiler"
    keywords = "Kyle Rassweiler Portfolio"
    copyright = "Kyle Rassweiler"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    contentDir = "content/en"

    [languages.en.params.logo]
      logoText = "Kyle Rassweiler"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "software"
        name = "Software"
        url = "/software"
      [[languages.en.menu.main]]
        identifier = "design"
        name = "Design"
        url = "/design"
      [[languages.en.menu.main]]
        identifier = "hardware"
        name = "Hardware"
        url = "/hardware"

  # [languages.fr]
  #   languageName = "French"
  #   title = "Kyle Rassweiler"
  #   subtitle = "Portefeuille logiciel"
  #   owner = "Kyle Rassweiler"
  #   keywords = "Kyle Rassweiler Portefeuille"
  #   copyright = "Kyle Rassweiler 2021"
  #   menuMore = "View Plus"
  #   readMore = "Lire Plus"
  #   readOtherPosts = "Read other posts"
  #   newerPosts = "Nouvaux Postes"
  #   olderPosts = "Vieux Postes"
  #   missingContentMessage = "Page n'existe pas..."
  #   missingBackButtonLabel = "Retourne au page d'accueil"
  #   contentDir = "content/fr"

  #   [languages.fr.params.logo]
  #     logoText = "Kyle Rassweiler"
  #     logoHomeLink = "/"

  #   [languages.fr.menu]
  #     [[languages.fr.menu.main]]
  #       identifier = "about"
  #       name = "à propos"
  #       url = "/fr/about"
  #     [[languages.fr.menu.main]]
  #       identifier = "software"
  #       name = "logiciel"
  #       url = "/fr/software"
  #     [[languages.fr.menu.main]]
  #       identifier = "design"
  #       name = "dessin"
  #       url = "/fr/design"
  #     [[languages.fr.menu.main]]
  #       identifier = "hardware"
  #       name = "matériel"
  #       url = "/fr/hardware"
