baseURL = 'https://wwww.kylerassweiler.ca'
languageCode = 'en-us'
title = 'Kyle Rassweiler'
subtitle = "A sleek software portfolio"
owner = "Kyle Rassweiler"
keywords = "Kyle Rassweiler Portfolio"
copyright = "Kyle Rassweiler"
theme = 'ananke'
#RelativeURLs = true
#CanonifyURLs = true
DefaultContentLanguage = "en"
paginate = 10
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    title = "Kyle Rassweiler"
    weight = 1
    contentDir = "content/"

[params]
  author = "Kyle Rassweiler"
  favicon = "/images/favicon.ico"
  site_logo = "/images/LogoXSmall.png"
  youtube = "https://www.youtube.com/user/Krassweiler"
  odysee = "https://odysee.com/@kylerassweiler"
  github = "https://github.com/rassweiler"
  gitlab = ""
  twitter = ""
  linkedin = "https://www.linkedin.com/in/kylerassweiler/"
  featured_image = "/images/cover.png"
  description = "A sleek software portfolio"
  facebook = ""
  instagram = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3
  skillSection = "Skills"
  mainSections = ["Software"]
  custom_css = ["custom.css"]

[menu]
[[menu.main]]
  identifier = 'About'
  name = 'About'
  url = '/about/'
  weight = -110
[[menu.main]]
  identifier = 'Software'
  name = 'Software'
  url = '/software/'
  weight = -109
[[menu.main]]
  identifier = 'Hardware'
  name = 'Hardware'
  url = '/hardware/'
  weight = -108
[[menu.main]]
  identifier = 'Design'
  name = 'Design'
  url = '/design/'
  weight = -107